# Generated by Django 3.2.8 on 2021-10-10 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='addreess',
            new_name='address',
        ),
    ]
